modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Szeweq/Flux/issues"
license="MIT"

[[mods]]
 modId="flux"
 version="${modVersion}"
 displayName="Flux Machinery"
 updateJSONURL="https://raw.githubusercontent.com/Szeweq/Flux/master/update.json"
 displayURL="https://www.curseforge.com/minecraft/mc-mods/flux"
 logoFile="flux_logo.png"
 credits="Szeweq"
 authors="Szeweq"
 description='''
Flux Machinery is a mod which provides energy to Vanilla blocks (like Furnace) without additional items.
It comes with useful machines that make item processing even more interesting.
'''

[[dependencies.flux]]
 modId="forge"
 mandatory=true
 versionRange="[35,)"
 ordering="NONE"
 side="BOTH"

[[dependencies.flux]]
 modId="minecraft"
 mandatory=true
 versionRange="[1.16.4,)"
 ordering="NONE"
 side="BOTH"

[[dependencies.flux]]
 modId="fl"
 mandatory=true
 versionRange="[4.3.2,)"
 ordering="BEFORE"
 side="BOTH"