modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Szeweq/Flux/issues"
license="MIT"

[[mods]]
 modId="fl"
 version="${coreVersion}"
 displayName="Flux Library"
 updateJSONURL="https://raw.githubusercontent.com/Szeweq/Flux/master/update-fl.json"
 displayURL="https://www.curseforge.com/minecraft/mc-mods/fl"
 credits="Szeweq"
 authors="Szeweq"
 description="Flux Library"

[[dependencies.fl]]
 modId="forge"
 mandatory=true
 versionRange="[35,)"
 ordering="NONE"
 side="BOTH"

[[dependencies.fl]]
 modId="minecraft"
 mandatory=true
 versionRange="[1.16.3,)"
 ordering="NONE"
 side="BOTH"